// Create User
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@gmail.com",
  "password": "admin123",
  "confPassword": "admin123",
  "role": "admin"
}

###
GET http://localhost:8080/api/v1/users

###
GET http://localhost:8080/api/v1/users/e9368f3f-849f-4ecb-9996-4e52e9bf9f65

###
PATCH http://localhost:8080/api/v1/users/915ef5cf-b896-490a-b026-16ae7f40a4d5
Content-Type: application/json

{
  "name": "user update",
  "email": "user@gmail.com",
  "password": "",
  "confPassword": "",
  "role": "user"
}

###
DELETE http://localhost:8080/api/v1/users/915ef5cf-b896-490a-b026-16ae7f40a4d5